version: "3.9"

services:
  recomendaciones_db:
    image: postgres:16
    container_name: recomendaciones_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123454321
      POSTGRES_DB: recomendaciones_db
    ports:
      - "5435:5432"
    volumes:
      - recomendaciones-data:/var/lib/postgresql/data
      - ./init/recomendaciones_init.sql:/docker-entrypoint-initdb.d/recomendaciones_init.sql
    restart: unless-stopped

volumes:
  recomendaciones-data: